### ISSUE TITLE
Auditing feedback: Tests are not run in independent context

### ISSUE THREAD

**Issue by kristovatlas** [gnolang/gno#2878] opened 2024-10-02 03:15 UTC
### Description

Feedback from a recent Gno auditor:

> The context of each test continues, making it difficult to test. In the case of Hardhat or Foundry tests, each test is initialized by a setup or before function and takes place in an independent context, whereas in the case of gno test, all tests are affected by previous test functions, making it tricky to use.

**Comment by leohhhn** [comment] 2024-10-02 07:55
Duplicate of https://github.com/gnolang/gno/issues/1982

**Closed** 2024-10-02 07:55 UTC
