### ISSUE TITLE
Incorrect conversion of integer to float in output

### ISSUE THREAD

**Issue by notJoon** [gnolang/gno#1379] opened 2023-11-17 03:06 UTC
## Description

```go
package main

func main() {
	var a int = 42
	println(float32(a))
}

// Expected:
// +4.200000e+001

// Output:
// 42
```

When running this code, the output is 42, not +4.200000e+001 as expected when an integer is converted to a float32. This seems to be a bug in the handling of FloatKind value conversion.

**Comment by thehowl** [comment] 2023-11-17 08:25
The numbers are actually the same. The first is 4.2 * 10, which is 42.

To me it seems more likely that we are printing things in this case more readable than go :)

Are you comparing with Go's println?

**Comment by thehowl** [comment] 2023-11-24 16:47
I'm closing this as "not a bug" for now.

As mentioned in https://github.com/gnolang/gno/issues/1377, I don't think striving for compatibility with Go's `println` is a useful endeavour, as the documentation for Go's println specifically says that it is implementation-specific.

If you can think of a good argument of why this should be the case -- or anyone reading this agrees that we should try to have `println`/`print` work in the same way as Go's format and can make a good argument for it, please reopen (or ask to reopen) this issue and make your case.

Personally, I think we'll obviously strive for 100% compatibility when we have the language-defined `fmt.Println`, but `println` seems like a non-goal. :)

**Closed by thehowl** 2023-11-24 16:47 UTC
