### ISSUE TITLE
Incorrect HTML Character Encoding in Source Code Display

### ISSUE THREAD

**Issue by grepsuzette** [gnolang/gno#2779] opened 2024-09-10 11:20 UTC
**Issue Description:**

When viewing source code on the website, certain characters such as `<` and `>` are being displayed as their HTML entity equivalents (`&lt;` and `&gt;`).  This can lead to confusion for users who are trying to read or copy the source code, as it does not accurately represent the original code.

**Steps to Reproduce:**
1. See for example https://gno.land/r/gnoland/blog/gnoblog_test.gno
2. Observe the representation of characters like `<` and `>` in the displayed code.

![ksnip_20240910-191423](https://github.com/user-attachments/assets/a55c00c6-5493-47c3-8373-e619e3a8122e)
Shown by gnoweb

![ksnip_20240910-191547](https://github.com/user-attachments/assets/d144ccc3-76e6-4410-834b-2312bdb7e5ff)
Actual code

**Expected Behavior:**
The source code should display the actual characters `<` and `>` instead of their HTML entity representations.

This is all the more important as we discussing filtering more HTML and it gives an appearance of complexity when there isn't.

**Comment by leohhhn** [comment] 2024-09-10 17:41
Hey, thanks for this; this partly a duplicate of #2746 & #2752. I'll close this issue. This will be fixed in the upcoming gnoweb revamp.

**Closed by leohhhn** 2024-09-10 17:41 UTC
