### ISSUE TITLE
gnoweb shows `&lt;` for `<` when browsing source code

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#2814] opened 2024-09-18 18:15 UTC
example: https://gno.land/p/demo/avl/node.gno

![image](https://github.com/user-attachments/assets/5bd73d1c-e7ef-4c10-bd7a-99e64460153d)

looks like we're escaping too much.

**Comment by leohhhn** [comment] 2024-09-18 19:28
Duplicate of #2746 #2752

**Closed by leohhhn** 2024-09-18 19:28 UTC
Labels: 🐞 bug, 🌍 gnoweb
