### ISSUE TITLE
Build failure when using `make install`

### ISSUE THREAD

**Issue by stefann-01** [gnolang/gno#3368] opened 2024-12-19 02:36 UTC
### Description

After pulling the latest [commit](https://github.com/gnolang/gno/commit/d69b5529e938f89b05b449fcd0a0bdcf7bcdc09e) from master, when using `make install` command, the installation fails during `gno` installation due to a type mismatch in the `BeginTransaction` function call. The compiler indicates that a required `GasMeter` argument is missing in the function call in the linting code.

### Your environment

* Go version go1.23.2
* OS and CPU architecture linux/amd64
* Gno commit hash causing the issue d69b5529e938f89b05b449fcd0a0bdcf7bcdc09e

### Steps to reproduce

1. Clone the Gno repository
2. Checkout commit d69b5529e938f89b05b449fcd0a0bdcf7bcdc09e
3. Run make install from the root directory
4. Build fails during the `gno` installation step

### Expected behaviour

The `make install` command should complete successfully.

### Actual behaviour

The build fails.

### Logs

```make --no-print-directory -C ./gno.land install.gnokey
go install ./cmd/gnokey
[+] 'gnokey' has been installed. Read more in ./gno.land/
make --no-print-directory -C ./gnovm    install
go install -ldflags "-X github.com/gnolang/gno/gnovm/pkg/gnoenv._GNOROOT=/home/stefan/gno_workspace/gno_orig/gno" ./cmd/gno
# github.com/gnolang/gno/gnovm/cmd/gno
cmd/gno/lint.go:147:34: not enough arguments in call to ts.BeginTransaction
        have ("github.com/gnolang/gno/tm2/pkg/store/types".Store, "github.com/gnolang/gno/tm2/pkg/store/types".Store)
        want ("github.com/gnolang/gno/tm2/pkg/store/types".Store, "github.com/gnolang/gno/tm2/pkg/store/types".Store, "github.com/gnolang/gno/tm2/pkg/store/types".GasMeter)
make[1]: *** [Makefile:43: install] Error 1
make: *** [Makefile:42: install.gno] Error 2```

**Comment by moul** [comment] 2024-12-19 08:41
CI on https://github.com/gnolang/gno/pull/3315 should have identified the issue.

**Comment by n0izn0iz** [comment] 2024-12-19 09:15
The problem is that [this PR](https://github.com/gnolang/gno/pull/3315) was merged without being based on latest master
It adds the [offending line](https://github.com/gnolang/gno/pull/3315/files#diff-9110cf5ebf9a1892c17bcd87c756e684baa62183867bf04cf9dd41548d0ce40cR147), but it was passing the CI because it did not have the gas meter changes in it's base 

The root problem is that we don't check that the branch is up to date. The full way to fix that is:
- don't allow to merge branches not up-to-date
- disallow any branch-protection bypass (for example "Allow maintainers to bypass branch protections" option)
- optional: enable merge queue to be able to merge PRs without having to maintain them up-to-date manually

I must warn that the merge queue has tradeoffs and requires to modify workflows files to also target the merge-queue as well as adding jobs as required in the config

**Comment by thehowl** [comment] 2024-12-20 22:13
Moving discussion to https://github.com/gnolang/gno/issues/3395, and closing this because the issue is fixed.

**Closed by thehowl** 2024-12-20 22:13 UTC
Labels: 🐞 bug
