### ISSUE TITLE
nil can be converted to invalid types (ie. int)

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1341] opened 2023-11-07 20:04 UTC
First discovered in https://github.com/gnolang/gno/pull/1177#issuecomment-1747914727 , I think I have forgotten to make an issue to track it separately.

Sample program:

```
package main

func main() {
        println(int(nil))
}

// Output: 0
```

`int(nil)` makes no sense and should not be accepted.

**Comment by notJoon** [comment] 2023-11-09 10:05
I tested it and It seems to be caused by the `nil` value passing through `ConvertTo` as `undefined` type.

If I try to do a type conversion with `var x int = nil`, I get an error that the type conversion is not possible. 

```go
func TestNilConvert(t *testing.T) {
	m := NewMachine("test", nil)
	c := `package test
func main() {
	var x float32 = nil
	println(int(x))
}`

	n := MustParseFile("main.go", c)
	m.RunFiles(n)
	m.RunMain()
}

// panic: cannot convert undefined to float32 
```

Of course, the expected behavior of original golang is that "cannot use nil as typed value in variable declaration", so maybe this should be another issue.

Based on these result, It looks like the problem occurs when `nil` value passes through as [tv.isUndefined](https://github.com/gnolang/gno/blob/master/gnovm/pkg/gnolang/values_conversions.go#L79C1-L81).

**Comment by notJoon** [comment] 2023-11-09 10:39
I have written the following test:
```go
package gnolang

func TestNilTypeConversion(t *testing.T) {
    m := NewMachine("test", nil)
    testCases := []struct {
        name string
        code string
    }{
        {
            name: "NilToInt",
            code: `package test
            func main(){
                println(int(nil))
            }`,
        },
       // converting to bool, and other types
    }

    for _, tc := range testCases {
        t.Run(tc.name, function(t *testing.T) {
            n := MustParseFile("main.go", tc.code)
            defer func() {
                if r := recover(); r != nil {
                    t.Logf("Recovered from panic as expected: %v", r)
                } else {
                    t.Errorf("Expected a panic for invalid type conversion")
                }
            }()
            m.RunFiles(n)
            m.RunMain()

            if err := m.CheckEmpty(); err != nil {
                t.Fatal(err)
            }
        })
    }
}
```
If the code is not changed, no error occurs and the test fails. However, if you make a panic in [ConvertTo](https://github.com/gnolang/gno/blob/master/gnovm/pkg/gnolang/values_conversions.go#L16) as below, the test passes.
```diff
    if tv.IsUndefined() {
+       panic(fmt.Sprintf(
+           "error: cannot convert undefined to %s",
+           t.String()))
-       tv.T = t
-       return
    }
```
It seems like the problem arises when a `nil` value is entered as `undefined` and then converted to a default type. My guess is, the issue could be resolved by preventing type conversion if `tv.T` is `nil` or modify the [IsUndefined](https://github.com/gnolang/gno/blob/c33c9f21b398538a9b6d30eabc33057c698b45e6/gnovm/pkg/gnolang/values.go#L933) function.

**Closed** 2024-01-10 13:17 UTC
Labels: :lady_beetle: bug, :package: :robot: gnovm
